/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.bibSys.apresentacao;

import br.unesp.rc.bibSys.beans.ReferenciaCompararBeans;
import br.unesp.rc.bibSys.beans.ReferenciaConcatenarBeans;
import br.unesp.rc.bibSys.businessObject.CompararArquivosBO;
import br.unesp.rc.bibSys.businessObject.ConcatenarArquivosBO;
import br.unesp.rc.bibSys.utils.ArquivosUtils;
import br.unesp.rc.bibSys.utils.ManagerGUI;
import static br.unesp.rc.bibSys.utils.ManagerGUI.centralizar;
import br.unesp.rc.bibSys.utils.ParserBibTex;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cesar
 */
public class JDialogComparar extends javax.swing.JDialog {

    /**
     * Creates new form JDialogComparar
     */
    public JDialogComparar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centralizar(this);
        gerenciarVisibilidadeBotaoComparar();
        gerenciarVisibilidadeBotaoConcatenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblArquivoB = new java.awt.Label();
        txtArquivoA = new java.awt.TextField();
        btnProcurarArqA = new java.awt.Button();
        label2 = new java.awt.Label();
        txtArquivoB = new java.awt.TextField();
        btnProcurarArqB = new java.awt.Button();
        txtComparar = new java.awt.TextArea();
        btnSalvar = new javax.swing.JButton();
        btnComparar = new javax.swing.JButton();
        btnConcatenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblArquivoB.setText("Arquivo B");

        txtArquivoA.setEditable(false);

        btnProcurarArqA.setLabel("Procurar");
        btnProcurarArqA.setName(""); // NOI18N
        btnProcurarArqA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarArqAActionPerformed(evt);
            }
        });

        label2.setText("Arquivo A");

        txtArquivoB.setEditable(false);

        btnProcurarArqB.setLabel("Procurar");
        btnProcurarArqB.setName(""); // NOI18N
        btnProcurarArqB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarArqBActionPerformed(evt);
            }
        });

        txtComparar.setEditable(false);

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        btnConcatenar.setText("Concatenar");
        btnConcatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtComparar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtArquivoA, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarArqA, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArquivoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArquivoB, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnComparar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcatenar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProcurarArqB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(473, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcurarArqA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArquivoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcurarArqB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArquivoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtArquivoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnComparar)
                    .addComponent(btnConcatenar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );

        lblArquivoB.getAccessibleContext().setAccessibleName("lblArquivoB");
        txtArquivoA.getAccessibleContext().setAccessibleName("txtArquivoA");
        btnProcurarArqA.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarArqAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarArqAActionPerformed
        txtArquivoA.setText(ManagerGUI.abrirSeletorArquivo());
        gerenciarVisibilidadeBotaoComparar();
        gerenciarVisibilidadeBotaoConcatenar();
    }//GEN-LAST:event_btnProcurarArqAActionPerformed

    private void btnProcurarArqBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarArqBActionPerformed
        txtArquivoB.setText(ManagerGUI.abrirSeletorArquivo());
        gerenciarVisibilidadeBotaoComparar();
        gerenciarVisibilidadeBotaoConcatenar();
        gerenciarVisibilidadeBotaoSalvar();
    }//GEN-LAST:event_btnProcurarArqBActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        CompararArquivosBO bo = new CompararArquivosBO();
        StringBuilder str = new StringBuilder();
        try {
            ReferenciaCompararBeans refList = bo.compararArquivos(txtArquivoA.getText(), txtArquivoB.getText());

            refList.getReferenciasA().forEach((t) -> {
                str.append(t.getBibKey()).append(System.lineSeparator());
            });

            str.append(System.lineSeparator()).append("----------------------------").append(System.lineSeparator());

            refList.getReferenciasB().forEach((t) -> {
                str.append(t.getBibKey()).append(System.lineSeparator());
            });

            txtComparar.setText(str.toString());
            gerenciarVisibilidadeBotaoSalvar();
        } catch (IOException ex) {
            Logger.getLogger(JDialogComparar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatenarActionPerformed
        ConcatenarArquivosBO concatenarBO = new ConcatenarArquivosBO();
        StringBuilder text = new StringBuilder();
        try {
            List<ReferenciaConcatenarBeans> concatList = concatenarBO.concatenarArquivos(txtArquivoA.getText(), txtArquivoB.getText());

            concatList.forEach((t) -> {
                text.append(ParserBibTex.jsonToBibTex(t.getReferencia())).append(System.lineSeparator());
            });

            txtComparar.setText(text.toString());
            gerenciarVisibilidadeBotaoSalvar();
        } catch (IOException ex) {
            Logger.getLogger(JDialogComparar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConcatenarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String path = ManagerGUI.abrirSeletorArquivo();
        try {
            if(path != null && !path.equals(""))
                ArquivosUtils.escreverArquivo(path, txtComparar.getText());
        } catch (IOException ex) {
            Logger.getLogger(JDialogComparar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void gerenciarVisibilidadeBotaoComparar(){
        btnComparar.setEnabled(!txtArquivoA.getText().equals("") && !txtArquivoB.getText().equals(""));
    }
    
    private void gerenciarVisibilidadeBotaoConcatenar(){
        btnConcatenar.setEnabled(!txtArquivoA.getText().equals("") && !txtArquivoB.getText().equals(""));
    }
    
    private void gerenciarVisibilidadeBotaoSalvar(){
        btnSalvar.setEnabled(!txtArquivoA.getText().equals("") 
                && !txtArquivoB.getText().equals("") 
                && !txtComparar.getText().trim().equals(""));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogComparar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogComparar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogComparar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogComparar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogComparar dialog = new JDialogComparar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnConcatenar;
    private java.awt.Button btnProcurarArqA;
    private java.awt.Button btnProcurarArqB;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private java.awt.Label lblArquivoB;
    private java.awt.TextField txtArquivoA;
    private java.awt.TextField txtArquivoB;
    private java.awt.TextArea txtComparar;
    // End of variables declaration//GEN-END:variables
}
